name: Pull LegiScan Datasets

on:
  schedule:
    - cron: '0 5 * * 1'  # every Monday at 5am UTC
  workflow_dispatch:     # manual trigger

jobs:
  pull-datasets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run LegiScan pull script
      run: |
        python scripts/download_legiscan.py

    - name: Commit and push dataset updates
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add datasets/
        git commit -m "Auto-update LegiScan datasets"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
