# .github/workflows/daily-case-studies.yml
name: Daily Liberation Technology Content Generation

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install feedparser requests anthropic python-dateutil
        
    - name: Generate content
      env:
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      run: python scripts/content_generator.py
      
    - name: Commit new content
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add drafts/
        git diff --staged --quiet || git commit -m "Daily content generation: $(date '+%Y-%m-%d')"
        git push
