name: Download LOC Images

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run image downloader
        run: python scripts/download_images.py

      - name: Commit and push new images
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add images/
          if git diff --cached --quiet; then
            echo "No new images to commit."
          else
            git commit -m "Add downloaded LOC images [auto]"
            git push