name: RSS FEEDS 

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests urllib3

      - name: Run LOC fetch combined script
        run: python scripts/content_generator.py

      - name: Commit new content
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add _posts images
          git diff --cached --quiet || git commit -m "Add LOC text and images [auto]"
          git push
