name: LOC Combined Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # daily at 12:00 UTC

jobs:
  fetch-loc-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run LOC Text Fetch Script
      run: python scripts/loc_dignity.py

    - name: Run LOC Image Fetch Script
      run: python scripts/loc_dignity.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add -A

        if git diff --cached --quiet; then
          echo "No changes to commit."
          exit 0
        fi

        git commit -m "Add LOC posts (text + images) [auto]"
        git push
