name: Library of Congress Content Generation

on:
  schedule:
    - cron: '0 10,22 * * *'  # Twice a day (10 AM & 10 PM UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-loc-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run LOC dignity script
        run: python scripts/loc_dignity_search.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull --rebase
          git add _posts
          git diff --staged --quiet || (git commit -m "Add LOC dignity posts: $(date +%Y-%m-%dT%H:%M:%S)" && git push)