- name: Commit and push LOC posts
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    git pull --rebase origin main
    git add _posts/
    git commit -m "Add new LOC posts [auto]" || echo "No changes to commit"
    git push origin main
